name: sabormaps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.0
  http: ^0.13.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/im1.jpg
    - images/icons.png
    - assets/2.jpg
    - assets/1.jpg
    - assets/3.jpeg
    - assets/4.jpg
    - assets/5.jpeg
    - assets/6.jpg


