name: sabormaps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.2.0
  http: ^0.13.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.4
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - images/im1.jpg
    - images/icons.png
    - assets/2.jpg
    - assets/1.jpg
    - assets/3.jpeg
    - assets/4.jpg
    - assets/5.jpeg
    - assets/6.jpg
flutter_launcher_icons:
  image_path_android: "assets/icon/icon.png"  # Ruta del icono para Android
  android: true  # Solo generar iconos para Android
  adaptive_icon_background: "assets/icon/icon.png"  # Solo para Android 8.0+
  adaptive_icon_foreground: "assets/icon/icon.png"  # Solo para Android 8.0+
  adaptive_icon_foreground_inset: 16  # Solo para Android 8.0+
  min_sdk_android: 21  # Asegura que la versión mínima sea 21 o superior



