// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6omF-FimVmd-Vte78sD17TtCI7cWDA4',
    appId: '1:1054373527184:web:c68e2a5835f679decee215',
    messagingSenderId: '1054373527184',
    projectId: 'sabormaps-907d4',
    authDomain: 'sabormaps-907d4.firebaseapp.com',
    storageBucket: 'sabormaps-907d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrJpacUgxwtQQQU16677S3A9bGUOyqbBQ',
    appId: '1:1054373527184:android:bed34bce2e30e27fcee215',
    messagingSenderId: '1054373527184',
    projectId: 'sabormaps-907d4',
    storageBucket: 'sabormaps-907d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQ5uduPqFuDWn_OjevVOP7aRsv8xfV8s',
    appId: '1:1054373527184:ios:dc9ccfe9561b5bcbcee215',
    messagingSenderId: '1054373527184',
    projectId: 'sabormaps-907d4',
    storageBucket: 'sabormaps-907d4.appspot.com',
    iosBundleId: 'com.example.sabormaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmQ5uduPqFuDWn_OjevVOP7aRsv8xfV8s',
    appId: '1:1054373527184:ios:dc9ccfe9561b5bcbcee215',
    messagingSenderId: '1054373527184',
    projectId: 'sabormaps-907d4',
    storageBucket: 'sabormaps-907d4.appspot.com',
    iosBundleId: 'com.example.sabormaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU6omF-FimVmd-Vte78sD17TtCI7cWDA4',
    appId: '1:1054373527184:web:591b428ca77c18d6cee215',
    messagingSenderId: '1054373527184',
    projectId: 'sabormaps-907d4',
    authDomain: 'sabormaps-907d4.firebaseapp.com',
    storageBucket: 'sabormaps-907d4.appspot.com',
  );

}